[package]
name = "instar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.26"
tar = "0.4.38"
clap = { version = "4.3.10", features = ["derive"] }
path-absolutize = "3.1.0"

